services:
  db:
    image: mariadb:10.11
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${DB_ROOT_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - onlyoffice
    ports:
      - "23306:3306"

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--databases", "1", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - ./redis:/data
    networks:
      - onlyoffice

  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    restart: unless-stopped
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
      JWT_HEADER: Authorization
    expose:
      - "80"
    volumes:
      - ./data/onlyoffice/document_data:/var/www/onlyoffice/Data
      - ./data/onlyoffice/document_log:/var/log/onlyoffice
      - ./data/onlyoffice/document_lib:/var/lib/onlyoffice
      - ./data/onlyoffice/document_db:/var/lib/postgresql
    networks:
      - onlyoffice

  app:
    image: owncloud/server:latest
    container_name: app-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      onlyoffice-document-server:
        condition: service_started
    environment:
      OWNCLOUD_DOMAIN: ${OWNCLOUD_DOMAIN}
      OWNCLOUD_TRUSTED_DOMAINS: ${OWNCLOUD_TRUSTED_DOMAINS}
      OWNCLOUD_OVERWRITE_CLI_URL: ${OWNCLOUD_OVERWRITE_CLI_URL}
      OWNCLOUD_ADMIN_USERNAME: ${ADMIN_USERNAME}
      OWNCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: ${DB_NAME}
      OWNCLOUD_DB_USERNAME: ${DB_USERNAME}
      OWNCLOUD_DB_PASSWORD: ${DB_PASSWORD}
      OWNCLOUD_DB_HOST: db
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: redis
      ONLYOFFICE_JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
    expose:
      - "8080"
    volumes:
      - ./files:/mnt/data
      - ./onlyoffice:/tmp/onlyoffice:ro
      - ./run.sh:/run.sh:ro
    command: ["bash", "/run.sh"]
    networks:
      - onlyoffice

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    depends_on:
      - app
      - onlyoffice-document-server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - onlyoffice

networks:
  onlyoffice:
    driver: bridge
